theme: jekyll-theme-minimal
title: "Ariel I. Morada Jr."
logo: "/assets/images/skills-agile.png"
description: "Software Engineer"
navigation:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Contact"
    link: "/contact"
email: aimoradajr9@gmail.com
github_url: https://github.com/aimoradajr
linkedin_url: https://www.linkedin.com/in/aimoradajr
codepen_url: https://codepen.io/Ariel-Morada