theme: jekyll-theme-minimal
title: "Ariel I. Morada Jr."
description: "Software Engineer | Angular, NodeJS"
navigation:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Contact"
    link: "/contact"
github_url: https://github.com/aimoradajr
linkedin_url: https://www.linkedin.com/in/aimoradajr
codepen_url: https://codepen.io/your-codepen-username
